channels:
  - conda-forge
dependencies:
  - python =3.9
  - numpy =1.20
  - scipy =1.6
  - matplotlib =3.3
  - jupyter =1.0
  - astropy =4.2
  - astroquery =0.4
  - pip =21.0
  - pip:
      - kepler.py==0.0.6
      - numpyro==0.5.0
