name: Paper

on:
  pull_request:
  push:
    branches: [main]

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Compile
        uses: docker://texlive/texlive:latest
        with:
          entrypoint: .github/scripts/compile-paper.sh
      - uses: actions/upload-artifact@v2
        with:
          name: paper
          path: paper/one-datum.pdf
      - name: Push compiled PDFs
        if: ${{ github.event_name != 'pull_request' }}
        continue-on-error: true
        run: |
          git checkout --orphan ${GITHUB_REF##*/}-pdf
          git rm --cached -rf .
          git add -f paper/one-datum.pdf
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "updating pdf"
          git push --force https://github.com/$GITHUB_REPOSITORY ${GITHUB_REF##*/}-pdf
