name: Paper

on:
  pull_request:
  push:
    branches: [main]

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./paper/figures/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/dfm/one-datum-figures:latest
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      # Generate the figures
      - name: Figures
        run: docker run --rm -v $(pwd):/workspace --workdir /workspace ghcr.io/dfm/one-datum-figures:latest

      # Compile the PDF using TeXLive
      - name: Paper
        uses: docker://texlive/texlive:latest
        with:
          entrypoint: .github/scripts/compile-paper.sh

      # Upload the PDF and figures as an artifact. This is useful for PRs where the results
      # don't get pushed to a branch
      - uses: actions/upload-artifact@v2
        with:
          name: paper
          path: |
            paper/one-datum.pdf
            paper/figures/githash.tex
            paper/figures/*.pdf

      # If this isn't a pull request, force push the PDF to an orphan branch
      - name: Push compiled PDF
        if: ${{ github.event_name != 'pull_request' }}
        continue-on-error: true
        run: |
          git checkout --orphan ${GITHUB_REF##*/}-pdf
          git rm --cached -rf .
          git add -f LICENSE
          git add -f paper/one-datum.pdf
          git add -f paper/figures/githash.tex
          git add -f paper/figures/*.pdf
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "updating pdf"
          git push --force https://github.com/$GITHUB_REPOSITORY ${GITHUB_REF##*/}-pdf
