name: Paper

on:
  pull_request:
  push:
    branches: [main]

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        uses: docker://texlive/texlive:latest
        with:
          args: cd paper; make
      - uses: actions/upload-artifact@v2
        with:
          name: paper
          path: paper/one-datum.pdf
