name: Paper

on:
  workflow_run:
    workflows: ["Docker"]
    branches:
      - main
    types:
      - completed

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Generate the figures
      - name: Figures
        uses: docker://ghcr.io/dfm/one-datum:main
        # uses: ./
        with:
          entrypoint: paper/figures/make-figures.sh

      # Compile the PDF using TeXLive
      - name: Paper
        uses: docker://texlive/texlive:latest
        with:
          entrypoint: .github/scripts/compile-paper.sh

      # Upload the PDF and figures as an artifact. This is useful for PRs where the results
      # don't get pushed to a branch
      - uses: actions/upload-artifact@v2
        with:
          name: paper
          path: |
            paper/one-datum.pdf
            paper/figures/githash.tex
            paper/figures/*.pdf

      # If this isn't a pull request, force push the PDF to an orphan branch
      - name: Push compiled PDF
        if: ${{ github.event_name != 'pull_request' }}
        continue-on-error: true
        run: |
          git checkout --orphan ${GITHUB_REF##*/}-pdf
          git rm --cached -rf .
          git add -f LICENSE
          git add -f paper/one-datum.pdf
          git add -f paper/figures/githash.tex
          git add -f paper/figures/*.pdf
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "updating pdf"
          git push --force https://github.com/$GITHUB_REPOSITORY ${GITHUB_REF##*/}-pdf
